In [1]:
import pandas as pd
from leetcode_scrape import getData

ModuleNotFoundError: No module named 'pandas'

In [2]:
!pip3 install pandas

Collecting pandas
  Downloading https://files.pythonhosted.org/packages/1c/11/e1f53db0614f2721027aab297c8afd2eaf58d33d566441a97ea454541c5e/pandas-1.1.2-cp36-cp36m-manylinux1_x86_64.whl (10.5MB)
    100% |████████████████████████████████| 10.5MB 135kB/s eta 0:00:01
Collecting numpy>=1.15.4 (from pandas)
  Downloading https://files.pythonhosted.org/packages/b8/e5/a64ef44a85397ba3c377f6be9c02f3cb3e18023f8c89850dd319e7945521/numpy-1.19.2-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
    100% |████████████████████████████████| 13.4MB 105kB/s eta 0:00:01
Collecting pytz>=2017.2 (from pandas)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting python-dateutil>=2.7.3 (from pandas)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.7.3->pandas)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: numpy, pytz, six, python-dateutil, pandas
Successfully installed numpy-1.19.2 pandas-1.1.2 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0

In [5]:
!pip3 install scikit-learn

Collecting scikit-learn
  Downloading https://files.pythonhosted.org/packages/5c/a1/273def87037a7fb010512bbc5901c31cfddfca8080bc63b42b26e3cc55b3/scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 199kB/s eta 0:00:01
Collecting numpy>=1.13.3 (from scikit-learn)
  Using cached https://files.pythonhosted.org/packages/b8/e5/a64ef44a85397ba3c377f6be9c02f3cb3e18023f8c89850dd319e7945521/numpy-1.19.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=0.19.1 (from scikit-learn)
  Downloading https://files.pythonhosted.org/packages/2b/a8/f4c66eb529bb252d50e83dbf2909c6502e2f857550f22571ed8556f62d95/scipy-1.5.2-cp36-cp36m-manylinux1_x86_64.whl (25.9MB)
    100% |████████████████████████████████| 25.9MB 53kB/s  eta 0:00:01
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Downloading https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Collecting joblib>=0.11 (from scikit-learn)
  Downloading https://files.pythonhosted.org/packages/fc/c9/f58220ac44a1592f79a343caba12f6837f9e0c04c196176a3d66338e1ea8/joblib-0.17.0-py3-none-any.whl (301kB)
    100% |████████████████████████████████| 307kB 4.8MB/s eta 0:00:01
Installing collected packages: numpy, scipy, threadpoolctl, joblib, scikit-learn
Successfully installed joblib-0.17.0 numpy-1.19.2 scikit-learn-0.23.2 scipy-1.5.2 threadpoolctl-2.1.0

In [102]:
df = pd.read_csv('./userDatabase.csv')
userLeetcode_Datas = []
for i in df['LeetCode_User']:
    userLeetcode_Datas.append(getData(i))

df_leetcode = pd.DataFrame(userLeetcode_Datas)
df_leetcode.to_csv('leetcode_usr_data.csv',index=False)

/Users/tanaysinghania/Documents/CODING/leetcode_leaderboard/leetcode_scrape.py:8: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 8 of the file /Users/tanaysinghania/Documents/CODING/leetcode_leaderboard/leetcode_scrape.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(html_doc)

In [1]:
from bs4 import BeautifulSoup
import requests

In [ ]:
def getData(handle):
    url = 'https://codeforces.com/api/user.rating?handle={}/'.format(handle)
    r = requests.get(url)
    html_doc = r.text
    soup = BeautifulSoup(html_doc)
    
    
    
    
    rows = soup.find_all('span','badge')
    ans = []
    c1 = eval(rows[0].text.strip())
    if c1==0:
        ans = rows[1:4]
    else:
        ans = rows[3:6]

    ans = [x.text.strip() for x in ans]

    dic = {'User' : userID,
        'Solved Questions' : int(ans[0][:ans[0].find('/')].strip()),
           'Total Questions' : int(ans[0][ans[0].find('/')+1:].strip()),
          'Accepted Submissions' : int(ans[1][:ans[1].find('/')].strip()),
           'Total Submissions' : int(ans[1][ans[1].find('/')+1:].strip()),
          'Acceptance Rate' : eval(ans[2][:ans[2].find('%')].strip())}
    
    return dic

In [47]:
userData = []
userDB = pd.read_csv('./userDatabase.csv')
for x in userDB['Codeforces_User']:    
    url = 'https://codeforces.com/api/user.rating?handle={}'.format(x)
    r = requests.get(url)
    json = r.json()
    userData += json['result']

df = pd.DataFrame(userData)
df = df.set_index(['handle'])
df.to_csv('codeforces_DB.csv')

In [45]:
df

,contestId,contestName,rank,ratingUpdateTimeSeconds,oldRating,newRating
handle,,,,,,
mrBansal,1141,Codeforces Round #547 (Div. 3),3485,1553013300,0,1430
mrBansal,1283,Codeforces Round #611 (Div. 3),564,1577559900,1430,1501
mrBansal,1270,Good Bye 2019,4301,1577639100,1501,1466
mrBansal,1287,Codeforces Round #612 (Div. 2),1779,1578240300,1466,1487
mrBansal,1291,Codeforces Round #616 (Div. 2),5284,1580661300,1487,1417
mrBansal,1296,Codeforces Round #617 (Div. 3),707,1580834100,1417,1508
mrBansal,1301,Codeforces Round #619 (Div. 2),1114,1581611700,1508,1591
mrBansal,1311,Codeforces Round #624 (Div. 3),1575,1582562100,1591,1566
mrBansal,1328,Codeforces Round #629 (Div. 3),260,1585240500,1566,1681
mrBansal,1341,"Codeforces Round #637 (Div. 2) - Thanks, Ivan ...",872,1587662100,1681,1747
mrBansal,1348,Codeforces Round #638 (Div. 2),3156,1588352700,1747,1724
tchala,1307,Codeforces Round #621 (Div. 1 + Div. 2),5738,1581961800,0,1405
tchala,1315,"Codeforces Round #623 (Div. 2, based on VK Cup...",399,1582482900,1405,1529
tchala,1325,Codeforces Round #628 (Div. 2),2534,1584203700,1529,1545
tchala,1332,Codeforces Round #630 (Div. 2),4500,1585670700,1545,1536
tchala,1330,"Codeforces Round #631 (Div. 2) - Thanks, Denis...",5389,1585931700,1536,1492
tchala,1333,Codeforces Round #632 (Div. 2),5100,1586363700,1492,1482
tchala,1334,Educational Codeforces Round 85 (Rated for Div...,2341,1586536500,1482,1553
tchala,1339,Codeforces Round #633 (Div. 2),1793,1586707500,1553,1594
tchala,1335,Codeforces Round #634 (Div. 3),813,1586795700,1594,1645
tchala,1337,Codeforces Round #635 (Div. 2),1207,1586970300,1645,1697
tchala,1371,Codeforces Round #654 (Div. 2),3439,1593617700,1697,1656

In [17]:
import pandas as pd

In [34]:
df.loc['mrBansal']

,contestId,contestName,rank,ratingUpdateTimeSeconds,oldRating,newRating
handle,,,,,,
mrBansal,1141,Codeforces Round #547 (Div. 3),3485,1553013300,0,1430
mrBansal,1283,Codeforces Round #611 (Div. 3),564,1577559900,1430,1501
mrBansal,1270,Good Bye 2019,4301,1577639100,1501,1466
mrBansal,1287,Codeforces Round #612 (Div. 2),1779,1578240300,1466,1487
mrBansal,1291,Codeforces Round #616 (Div. 2),5284,1580661300,1487,1417
mrBansal,1296,Codeforces Round #617 (Div. 3),707,1580834100,1417,1508
mrBansal,1301,Codeforces Round #619 (Div. 2),1114,1581611700,1508,1591
mrBansal,1311,Codeforces Round #624 (Div. 3),1575,1582562100,1591,1566
mrBansal,1328,Codeforces Round #629 (Div. 3),260,1585240500,1566,1681
mrBansal,1341,"Codeforces Round #637 (Div. 2) - Thanks, Ivan ...",872,1587662100,1681,1747
mrBansal,1348,Codeforces Round #638 (Div. 2),3156,1588352700,1747,1724